### ISSUE TITLE
Create big A, C, F as pixels with bright colors 

### ISSUE THREAD

**Issue by bridgettorres** [bridgettorres/Nightshade-Academy#69]

**Comment by spaghetus** [comment]
![Image](https://github.com/bridgettorres/Nightshade-Academy/assets/28763739/e46f998a-8c3b-47d2-b0f8-b8d42f89d5ef)
![Image](https://github.com/bridgettorres/Nightshade-Academy/assets/28763739/d6e65921-a77f-4592-86bf-dacc786f42a7)
![Image](https://github.com/bridgettorres/Nightshade-Academy/assets/28763739/f6b67831-1c05-43f7-a6e7-5705dffeb3c3)
![Image](https://github.com/bridgettorres/Nightshade-Academy/assets/28763739/7de595f6-f067-49e2-890f-c05fad392e09)
