### ISSUE TITLE
Create WASD keys as well as a Q and E key and a cursor sprite

### ISSUE THREAD

**Issue by bridgettorres** [bridgettorres/Nightshade-Academy#84]

**Comment by bridgettorres** [comment]
![keys](https://github.com/bridgettorres/Nightshade-Academy/assets/67389317/946003e4-e272-4b40-953c-98cb7f501767)
![New Piskel (1)](https://github.com/bridgettorres/Nightshade-Academy/assets/67389317/2142b16e-f62d-41e4-9af4-b57b3bfd1a21)

**Comment by tsoutonglang** [comment]
![cursor](https://github.com/bridgettorres/Nightshade-Academy/assets/29801746/5e495885-8452-44fb-b030-b4248a123352)
